import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage();
const errs = [];
p.on("console", (m) => { if (m.type() === "error") errs.push(m.text().slice(0,300)); });
p.on("pageerror", (e) => errs.push("PAGEERROR: " + String(e).slice(0,400)));
await p.goto("http://127.0.0.1:3980/", { waitUntil: "load", timeout: 60000 });
await p.waitForTimeout(10000);
console.log("live pool card:", await p.locator("text=Live pool").count());
console.log("tvl label:", await p.locator("text=Total value locked").count());
console.log("--- console errors ---"); errs.slice(0,10).forEach(e=>console.log("  ", e));
await b.close();
